var TokType;
(function (TokType) {
    TokType[TokType["Halt"] = 0] = "Halt";
    TokType[TokType["Nop"] = 1] = "Nop";
    TokType[TokType["Mov"] = 2] = "Mov";
    TokType[TokType["Inc"] = 3] = "Inc";
    TokType[TokType["Push"] = 4] = "Push";
    TokType[TokType["Pop"] = 5] = "Pop";
    TokType[TokType["Add"] = 6] = "Add";
    TokType[TokType["Sub"] = 7] = "Sub";
    TokType[TokType["Mul"] = 8] = "Mul";
    TokType[TokType["Div"] = 9] = "Div";
    TokType[TokType["Mod"] = 10] = "Mod";
    TokType[TokType["Cmp"] = 11] = "Cmp";
    TokType[TokType["Ld"] = 12] = "Ld";
    TokType[TokType["Str"] = 13] = "Str";
    TokType[TokType["Jmp"] = 14] = "Jmp";
    TokType[TokType["Jeq"] = 15] = "Jeq";
    TokType[TokType["Jne"] = 16] = "Jne";
    TokType[TokType["Jl"] = 17] = "Jl";
    TokType[TokType["Jg"] = 18] = "Jg";
    TokType[TokType["Jle"] = 19] = "Jle";
    TokType[TokType["Jge"] = 20] = "Jge";
    TokType[TokType["Call"] = 21] = "Call";
    TokType[TokType["Ret"] = 22] = "Ret";
    TokType[TokType["Print"] = 23] = "Print";
    TokType[TokType["PrintR"] = 24] = "PrintR";
    TokType[TokType["Number"] = 25] = "Number";
    TokType[TokType["Bytes"] = 26] = "Bytes";
    TokType[TokType["Definition"] = 27] = "Definition";
    TokType[TokType["Label"] = 28] = "Label";
    TokType[TokType["LabelDeref"] = 29] = "LabelDeref";
    TokType[TokType["Comma"] = 30] = "Comma";
    TokType[TokType["NewLine"] = 31] = "NewLine";
    TokType[TokType["Register"] = 32] = "Register";
    TokType[TokType["Eof"] = 33] = "Eof";
})(TokType || (TokType = {}));
export { TokType };
//# sourceMappingURL=types.js.map